FROM ubuntu:latest AS build

RUN apt-get update && apt-get install -y \
    golang-go \
    git \
    build-essential \
    && apt-get clean

WORKDIR /src

RUN git clone https://github.com/Ferozaffs/sledge

WORKDIR /src/sledge/

WORKDIR /src/sledge/serverhost
RUN go build .

RUN sed -i 's/STANDALONE/HOST/g' /src/sledge/client/app.js

#---------------------------------------
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    nginx \
    docker.io \
    && apt-get clean

RUN rm /etc/nginx/sites-enabled/default
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /src/sledge/client /app/client 
COPY --from=build /src/sledge/serverhost/serverhost /app/serverhost 
COPY --from=build /src/sledge/docker-compose-room.yml /app/docker-compose-room.yml
COPY start_host.sh /start_host.sh
RUN chmod +x /start_host.sh

EXPOSE 5500
EXPOSE 5501

CMD ["/start_host.sh"]