services:
  host:
    build:
      context: .
      dockerfile: Dockerfile-Host
    ports:
      - "5000:5500"
      - "5501:5501"
    volumes:
      - //var/run/docker.sock://var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
